---
title: "R Coding Standards for Reproducibility"
format:
  revealjs:
    self-contained: true
    css: styles.css
execute:
  echo: true
  eval: false
  warning: false
  message: false
---

## What is `renv`?

- `renv` is an *R* package that helps make *R* projects **reproducible**
- It records:
  - Exact package versions used
  - Where packages came from (CRAN, Bioconductor, GitHub)
  - The *R* version used
- This allows collaborators, reviewers, and your future self to recreate the same *R* package environment on a different machine or at a later time

## How `renv` manages packages

- **Global package cache**:
  - Stores one copy of each package version on your machine
  - Shared across *R* projects for a given user
  - Can be configured to be shared across users on servers
- **Project library** (`renv/library/`):
  - Is project-specific and contains links to packages in the cache
  - Should never be committed to git

This design saves disk space and ensures isolation between projects.

## How to start using `renv` in an R project

1.  Run `install.packages("renv")`  
2.  `renv::init()` scans project files (`.R`, `.Rmd`, `.qmd`, `.Rnw`) for required packages and their dependencies. Then it
    - Creates the project library `renv/library/`
    - Installs required packages into the cache (`renv::paths$cache()` gives the cache path)
    - Writes the lockfile `renv.lock` that contains *R* and *R* package metadata recording the state of the project library (and used to reproduce package environment by others or future self)
  
## How to start using `renv` in an R project
3. Commit the following to git:
    - `renv.lock`
    - `.Rprofile`
    - `renv/activate.R`
        - Ensures `renv` auto-activates when the project opens
    - `renv/settings.json`
        - Ensures `renv` behaves the same for all collaborators

## Maintaining `renv`

- Use `renv::install("pkgname")` to install a new package or update an installed package
- After installing or updating one or multiple packages, use `renv::snapshot()` to update `renv.lock`

## Steps to create/update project library after `renv.lock` has been created/updated (e.g., by a collaborator)

- `renv` automatically bootstraps itself (i.e., downloads and installs) when a project is first opened in which `renv` has been activated by a collaborator
    - `.Rprofile` is involved
- Use `renv::restore()` to update/reproduce package environment as specified by `renv.lock`

## Limitation of `renv`

- `renv` records the **R version** but does not install *R* for you
- Collaborators must install a compatible *R* version separately

## Notes about `renv`

- Read **Introduction to renv**:<br> <https://rstudio.github.io/renv/articles/renv.html>
- Don't edit `renv.lock` manually
- Don't commit `renv/library` to git
    - `renv::init()` handles this automatically by including `library/` in `renv/.gitignore`
    
## Advanced notes
- If project includes many files with no *R* code, consider adding them to `.renvignore` at the top level
    - E.g., add `figs/**` to ignore the folder `figs` and all its content
